from sqlalchemy import Boolean, Column, DateTime, Float, Integer, Numeric, String
from app.db.base import Base


class CompanyMaster(Base):
    __tablename__ = "company_master"
    __table_args__ = {"schema": "public"}

    fincode = Column(Integer, primary_key=True, autoincrement=False)

    # BSE fields
    scripcode = Column(Integer)
    scrip_name = Column(String(35))
    scrip_group = Column(String(10))
    bse_scrip_id = Column(String(100))
    bse_sublisting = Column(String(50))

    # Company fields
    compname = Column(String(255))
    s_name = Column(String(100))
    industry = Column(String(100))
    isin = Column(String(20))
    status = Column(String(20))

    # NSE fields
    symbol = Column(String(20), index=True)
    series = Column(String(10))
    securitytoken = Column(Integer)
    nse_sublisting = Column(String(50))

    # Optional metadata
    ind_code = Column(Integer)
    hse_code = Column(Integer)
    house = Column(String(50))
    rformat = Column(String(5))
    fformat = Column(String(5))
    fv = Column(Float)
    flag = Column(String(1))


class FinanceBS(Base):
    __tablename__ = "finance_bs"
    __table_args__ = {"schema": "public"}

    fincode = Column(Integer, primary_key=True, index=True)
    year_end = Column(Integer, primary_key=True)
    type = Column(String, primary_key=True)
    no_months = Column(Integer)
    unit = Column(String)
    share_capital = Column(Float)
    shares_warrants = Column(Float)
    shares_application_money = Column(Float)
    esop_outstanding = Column(Float)
    share_suspense = Column(Float)
    reserve = Column(Float)
    sharehoders_funds = Column(Float)
    deposits = Column(Float)
    borrowings = Column(Float)
    other_liabilities = Column(Float)
    total_sounces_funds = Column(Float)
    cash_balances_rbi = Column(Float)
    bank_call_money = Column(Float)
    investments = Column(Float)
    advances = Column(Float)
    gross_block = Column(Float)
    acc_depreciation = Column(Float)
    impairment_assets = Column(Float)
    lease_adj = Column(Float)
    cwip = Column(Float)
    other_assets = Column(Float)
    total_applications = Column(Float)
    contingent_liabilities = Column(Float)
    bills_for_collection = Column(Float)
    ltrm_borrowing = Column(Float)
    secured_loans = Column(Float)
    unsecured_loans_nf = Column(Float)
    net_def_tax_nf = Column(Float)
    oth_lt_liab = Column(Float)
    lt_trade_payables = Column(Float)
    lt_provisions = Column(Float)
    total_nonliab = Column(Float)
    trade_payables = Column(Float)
    current_liabilities_nf = Column(Float)
    st_borrowings = Column(Float)
    provisions = Column(Float)
    current_laib_prov_nf = Column(Float)
    total_sounces_funds_nf = Column(Float)
    non_current_assets = Column(Float)
    loan_non_cuurent_assets = Column(Float)
    net_block = Column(Float)
    cwip_nf = Column(Float)
    intang_assetunderdev = Column(Float)
    pre_operatieve_exps = Column(Float)
    assetsintransit = Column(Float)
    investments_nf = Column(Float)
    lt_loanadv = Column(Float)
    other_noc_assets = Column(Float)
    total_nonassets = Column(Float)
    current_investments = Column(Float)
    inventory = Column(Float)
    debtors = Column(Float)
    cash_bank = Column(Float)
    other_current_nf = Column(Float)
    loans_adv = Column(Float)
    currant_assets_nf = Column(Float)
    net_current_assets_nf = Column(Float)
    other_crnt_assets = Column(Float)
    misc_exps_not_wo = Column(Float)
    total_applications_nf = Column(Float)
    total_debt = Column(Float)
    total_debt_inclst_nf = Column(Float)
    book_nav_share = Column(Float)
    adj_bv = Column(Float)
    minority_interest = Column(Float)
    equity_authorised = Column(Float)
    equity_issued = Column(Float)
    equity_paidup = Column(Float)
    equity_forfeited = Column(Float)
    adj_equity = Column(Float)
    preference_capital = Column(Float)
    face_value = Column(Float)
    share_premium = Column(Float)
    capital_reserve = Column(Float)
    profit_loss = Column(Float)
    general_reserve = Column(Float)
    reserve_excl_revaluation = Column(Float)
    revaluation_reserve = Column(Float)
    demand_deposits = Column(Float)
    saving_deposits = Column(Float)
    term_fixed_deposits = Column(Float)
    current_deposits = Column(Float)
    recurring_deposits = Column(Float)
    borrowings_rbi = Column(Float)
    borrowings_banks = Column(Float)
    borrowings_goi = Column(Float)
    borrowings_fi = Column(Float)
    borrowings_bonds = Column(Float)
    borrowings_other = Column(Float)
    borrowings_outof_india = Column(Float)
    bills_payable = Column(Float)
    inter_oofice_adjustments_liabilities = Column(Float)
    interest_accrued = Column(Float)
    proposed_dividend = Column(Float)
    corporate_dividend_tax = Column(Float)
    cash_rbi = Column(Float)
    cash_in_hand = Column(Float)
    investments_india = Column(Float)
    goi_securities = Column(Float)
    equity_shares_corporate = Column(Float)
    debentures_bonds = Column(Float)
    subsidiaries_joint_ventures = Column(Float)
    mutual_funds_insurance_units = Column(Float)
    investments_outside_india = Column(Float)
    goi_securities_outside_india = Column(Float)
    subsidiaries_joint_ventures_outside_india = Column(Float)
    other_investments_outside_india = Column(Float)
    dimunition_investments = Column(Float)
    bills_purchased_discounted = Column(Float)
    cash_credit_overdraft = Column(Float)
    term_loans = Column(Float)
    finance_lease_hire_purchase = Column(Float)
    buildings = Column(Float)
    assets_despose = Column(Float)
    other_fix_assets = Column(Float)
    inter_office_adjustments_assets = Column(Float)
    interest_accrued_assets = Column(Float)
    advance_tax_tds = Column(Float)
    stationery_stamps = Column(Float)
    non_banking_assets = Column(Float)
    deferred_tax_assets = Column(Float)
    misc_expenditures_not_writtoff = Column(Float)
    claims_not_acknowledge_debt = Column(Float)
    outstanding_forward_exchange_contra = Column(Float)
    guarantees_constituents_india = Column(Float)
    guarantees_constituents_outside_india = Column(Float)
    acceptances_endorsements_obligations = Column(Float)
    non_convertible_debenture = Column(Float)
    conv_debenture_bnds = Column(Float)
    packing_credit = Column(Float)
    intercorpsecdeposits = Column(Float)
    term_loan_bank = Column(Float)
    term_loan_inst = Column(Float)
    fixed_deposits = Column(Float)
    loans_susidiaries = Column(Float)
    inter_corp_deposits = Column(Float)
    foreign_curr_convertible_notes = Column(Float)
    foreign_curr_long_term_loans = Column(Float)
    loans_bank = Column(Float)
    loans_govt = Column(Float)
    loans_others = Column(Float)
    def_tax_assets = Column(Float)
    def_tax_liability = Column(Float)
    sundry_crs = Column(Float)
    acceptances = Column(Float)
    trade_paysubs = Column(Float)
    bank_od = Column(Float)
    adv_customers = Column(Float)
    interest_not_due = Column(Float)
    share_application = Column(Float)
    cl_curmat_deb = Column(Float)
    cl_curmat_others = Column(Float)
    loans = Column(Float)
    stbs_sec_loandemand = Column(Float)
    stbs_wcap = Column(Float)
    stbu_buycredit = Column(Float)
    stbu_commborr = Column(Float)
    proposed_divided = Column(Float)
    prov_corp_tax = Column(Float)
    prov_tax = Column(Float)
    prov_retirements = Column(Float)
    prefence_dividend = Column(Float)
    long_term_investments_nf = Column(Float)
    long_term_quoted = Column(Float)
    long_term_unquoted = Column(Float)
    current_quoted = Column(Float)
    raw_material = Column(Float)
    wip = Column(Float)
    fin_goods = Column(Float)
    packing_materials_inventory = Column(Float)
    store_spares = Column(Float)
    drs_six_months = Column(Float)
    drs_others = Column(Float)
    cash_hand = Column(Float)
    bank_balance = Column(Float)
    interest_investments = Column(Float)
    interest_debentures = Column(Float)
    deposits_govt_other = Column(Float)
    interest_accrued_due = Column(Float)
    prepaid_exps = Column(Float)
    adv_cash_kind = Column(Float)
    adv_tax = Column(Float)
    due_director = Column(Float)
    due_subsidiaries = Column(Float)
    inter_corporate_deposits = Column(Float)
    corporate_deposits = Column(Float)
    flag = Column(String)


class StockExchangeMaster(Base):
    __tablename__ = "stockexchangemaster"
    __table_args__ = {"schema": "public"}

    stk_id = Column(Integer, primary_key=True)
    stk_name = Column(String)
    flag = Column(String)


class RegistrarMaster(Base):
    __tablename__ = "registrarmaster"
    __table_args__ = {"schema": "public"}

    registrarno = Column(Integer, primary_key=True)
    registrarname = Column(String)
    regaddress = Column(String)
    registraraddress1 = Column(String)
    registraraddress2 = Column(String)
    registraraddress3 = Column(String)
    registrarphone = Column(String)
    registrarfax = Column(String)
    registraremail = Column(String)
    registrarwebsite = Column(String)
    flag = Column(String)


class Board(Base):
    __tablename__ = "board"
    __table_args__ = {"schema": "public"}

    fincode = Column(Integer, primary_key=True, index=True)
    yrc = Column(Integer, primary_key=True)
    serialno = Column(Integer, primary_key=True)
    dirtype_id = Column(Integer)
    srno = Column(Integer)
    effect_date = Column(DateTime)
    dirname = Column(String)
    directorid = Column(Integer)
    reported_dsg = Column(String)
    independent = Column(String)
    dirrem = Column(Float)
    rem_unit = Column(Float)
    flag = Column(String)


class FinanceCF(Base):
    __tablename__ = "finance_cf"
    __table_args__ = {"schema": "public"}

    fincode = Column(Integer, primary_key=True, index=True)
    year_end = Column(Integer, primary_key=True)
    type = Column(String, primary_key=True)
    no_months = Column(Integer)
    unit = Column(String)
    profit_bef_tax = Column(Float)
    adjustment_total = Column(Float)
    change_wc_total = Column(Float)
    tax_paid = Column(Float)
    other_dir_exps = Column(Float)
    cash_from_operation = Column(Float)
    cash_from_investment = Column(Float)
    cash_from_financing = Column(Float)
    fexchdiff = Column(Float)
    net_cash_inflow_outflow = Column(Float)
    opening_cash = Column(Float)
    cash_amalgmation = Column(Float)
    cash_subsidiaries = Column(Float)
    traslation_adj_subsidiaries = Column(Float)
    effect_foreign_exchange = Column(Float)
    closing_cash = Column(Float)
    cashflow_after_wc = Column(Float)
    flag = Column(String)


class FinancePL(Base):
    __tablename__ = "finance_pl"
    __table_args__ = {"schema": "public"}

    fincode = Column(Integer, primary_key=True, index=True)
    year_end = Column(Integer, primary_key=True)
    type = Column(String, primary_key=True)
    no_months = Column(Integer)
    unit = Column(String)
    interest_earned = Column(Float)
    other_income = Column(Float)
    total_income = Column(Float)
    interest = Column(Float)
    operating_expenses = Column(Float)
    provisions_contigency = Column(Float)
    tax = Column(Float)
    total = Column(Float)
    profit_after_tax = Column(Float)
    extra_items = Column(Float)
    profit_brought_forward = Column(Float)
    minority_interest = Column(Float)
    share_associate = Column(Float)
    other_consitems = Column(Float)
    consolidated_netprofit = Column(Float)
    adj_net_profit = Column(Float)
    extr_items = Column(Float)
    pnlbf = Column(Float)
    profit_availble_appr = Column(Float)
    appropriation = Column(Float)
    dividend_perc = Column(Float)
    reported_eps = Column(Float)
    sales = Column(Float)
    gross_sales = Column(Float)
    net_sales = Column(Float)
    inc_dec_inventory = Column(Float)
    raw_matrs_consumed = Column(Float)
    employees = Column(Float)
    other_mfg_exps = Column(Float)
    sellg_admn_exps = Column(Float)
    misc_exps = Column(Float)
    pre_op_exps = Column(Float)
    total_expendiure = Column(Float)
    operating_profit = Column(Float)
    depreciation = Column(Float)
    profit_before_exception = Column(Float)
    exceptionalincome_expenses = Column(Float)
    profit_before_tax = Column(Float)
    taxation = Column(Float)
    profit_available_appropriation = Column(Float)
    total_gross_sales = Column(Float)
    excise = Column(Float)
    power_fuel = Column(Float)
    pbdt = Column(Float)
    gross_profits = Column(Float)
    inter_div_trf = Column(Float)
    sales_return = Column(Float)
    sellg_exps = Column(Float)
    cost_sw = Column(Float)
    provision_investment = Column(Float)
    provision_advances = Column(Float)
    provision_other = Column(Float)
    curr_tax = Column(Float)
    def_tax = Column(Float)
    fringe_benefits = Column(Float)
    wealth_tax = Column(Float)
    interest_advances_bills = Column(Float)
    job_works = Column(Float)
    service_income = Column(Float)
    opening_rm = Column(Float)
    purchases_rm = Column(Float)
    closing_rm = Column(Float)
    purchases_fg = Column(Float)
    electricity = Column(Float)
    oils_fuels = Column(Float)
    coals = Column(Float)
    salaries = Column(Float)
    providend_fund_contri = Column(Float)
    staff_welfare = Column(Float)
    sub_contract = Column(Float)
    processing_charges = Column(Float)
    repairs_maintenance = Column(Float)
    upkeep_maintenance = Column(Float)
    upkeep_service = Column(Float)
    rent_rates_taxes = Column(Float)
    insurance = Column(Float)
    priting_stationery = Column(Float)
    professional_charges = Column(Float)
    travelling = Column(Float)
    advertising = Column(Float)
    commission_incentives = Column(Float)
    freight_forwardings = Column(Float)
    handling_clearing = Column(Float)
    bad_debts = Column(Float)
    prov_doubtfull_debts = Column(Float)
    loss_fixed_assets = Column(Float)
    loss_foreign_exchange = Column(Float)
    loss_sale_investment = Column(Float)
    interest_income = Column(Float)
    dividend_income = Column(Float)
    profit_fa = Column(Float)
    profit_investment = Column(Float)
    prov_written_back = Column(Float)
    foreign_exchange_gain = Column(Float)
    interest_deb = Column(Float)
    interest_term_loans = Column(Float)
    interest_fixed_deposits = Column(Float)
    bank_charges = Column(Float)
    appropriation_general_reserve = Column(Float)
    proposed_equity_devided = Column(Float)
    corp_divd_tax = Column(Float)
    eps = Column(Float)
    adj_eps = Column(Float)
    interest_rbi = Column(Float)
    interest_investment = Column(Float)
    income_jv_subs = Column(Float)
    rent_income = Column(Float)
    interest_rbi_borrowings = Column(Float)
    interest_other = Column(Float)
    depreciation_leased_assets = Column(Float)
    auditor_payment = Column(Float)
    telephone = Column(Float)
    repairs_other_admin = Column(Float)
    statutory_reserve = Column(Float)
    appropriation_revenue_reserve = Column(Float)
    other_appropriation = Column(Float)
    sale_shares_units = Column(Float)
    interest_earned_loan = Column(Float)
    portfolio_mgt_income = Column(Float)
    dividend_earned = Column(Float)
    brokerage_commission = Column(Float)
    processing_fees = Column(Float)
    depository_charges = Column(Float)
    security_trasaction_tax = Column(Float)
    software_technical_charges = Column(Float)
    provision_contigency = Column(Float)
    provision_npa = Column(Float)
    other_interest_income = Column(Float)
    commision = Column(Float)
    discounts = Column(Float)
    other_investmnet_income = Column(Float)
    income_diagnostic = Column(Float)
    cash_discount = Column(Float)
    consultant_changes = Column(Float)
    packing_materials = Column(Float)
    freight_outward = Column(Float)
    room_restaurents = Column(Float)
    communication_income = Column(Float)
    foods_beverage_sales = Column(Float)
    linen_room_supplies = Column(Float)
    catering_supplies = Column(Float)
    laundry_washing_expenses = Column(Float)
    music_banquest_restaurants = Column(Float)
    packing_expemses = Column(Float)
    sales_property_development = Column(Float)
    broadcasting_revenue = Column(Float)
    adverisement_revenue = Column(Float)
    licence_income = Column(Float)
    subscription_income = Column(Float)
    contents_film_income = Column(Float)
    program_production_exps = Column(Float)
    telecastin_expenses = Column(Float)
    programs_films_right = Column(Float)
    transmission_epc = Column(Float)
    wheeling_transmission = Column(Float)
    power_purchased = Column(Float)
    power_project_cost = Column(Float)
    wheeling_charges = Column(Float)
    spare_consumed = Column(Float)
    sub_contract_charges = Column(Float)
    development_rights = Column(Float)
    development_charges = Column(Float)
    income_investment_property = Column(Float)
    development_rights_cost = Column(Float)
    shipbuilding_income = Column(Float)
    charter_income = Column(Float)
    freight_income = Column(Float)
    stevedoreage_cargo_expenses = Column(Float)
    port_charges = Column(Float)
    sale_licenses = Column(Float)
    traded_sw = Column(Float)
    tech_fees = Column(Float)
    traing_exps = Column(Float)
    software_licences = Column(Float)
    travels_sw = Column(Float)
    insurance_sw = Column(Float)
    visa_charges = Column(Float)
    contract_support_sw = Column(Float)
    rates_taxes = Column(Float)
    sales_scrap = Column(Float)
    export_benefits = Column(Float)
    subsidy_incentives = Column(Float)
    freight_inward = Column(Float)
    hire_charges_mfg = Column(Float)
    donation = Column(Float)
    interest_other_income = Column(Float)
    commission = Column(Float)
    power_fuel_cost = Column(Float)
    royalty = Column(Float)
    project_expenses = Column(Float)
    flag = Column(String)


class FinanceFR(Base):
    __tablename__ = "finance_fr"
    __table_args__ = {"schema": "public"}

    fincode = Column(Integer, primary_key=True, index=True)
    year_end = Column(Integer, primary_key=True)
    type = Column(String, primary_key=True)
    reported_eps = Column(Float)
    adjusted_eps = Column(Float)
    ceps = Column(Float)
    dps = Column(Float)
    book_nav_share = Column(Float)
    tax_rate = Column(Float)
    core_ebitda_margin = Column(Float)
    ebit_margin = Column(Float)
    pre_tax_margin = Column(Float)
    pat_margin = Column(Float)
    cash_profit_margin = Column(Float)
    roa = Column(Float)
    roe = Column(Float)
    roce = Column(Float)
    asset_turnover = Column(Float)
    sales_fixed_asset = Column(Float)
    working_capital_sales = Column(Float)
    fixed_capital_sales = Column(Float)
    receivable_days = Column(Float)
    inventory_days = Column(Float)
    payable_days = Column(Float)
    per = Column(Float)
    pce = Column(Float)
    price_book = Column(Float)
    yield_ = Column("yield", Float)
    ev_net_sales = Column(Float)
    ev_core_ebitda = Column(Float)
    ev_ebit = Column(Float)
    ev_ce = Column(Float)
    mcap_sales = Column(Float)
    net_sales_growth = Column(Float)
    pbidt_excl_oi_growth = Column(Float)
    core_ebitda_growth = Column(Float)
    ebit_growth = Column(Float)
    pat_growth = Column(Float)
    adj_pat_growth = Column(Float)
    adj_eps_growth = Column(Float)
    reported_eps_growth = Column(Float)
    total_debt_equity = Column(Float)
    current_ratio = Column(Float)
    quick_ratio = Column(Float)
    interest_cover = Column(Float)
    total_debt_mcap = Column(Float)
    yield_adv = Column(Float)
    yield_inv = Column(Float)
    cost_liab = Column(Float)
    nim = Column(Float)
    int_spread = Column(Float)
    cost_incratio = Column(Float)
    core_cost_incratio = Column(Float)
    opcost_asset = Column(Float)
    adj_per = Column(Float)
    tier1ratio = Column(Float)
    tier2ratio = Column(Float)
    car = Column(Float)
    coreopincomegrowth = Column(Float)
    epsgrowth = Column(Float)
    bvpsgrowth = Column(Float)
    adv_growth = Column(Float)
    loandeposits = Column(Float)
    cashdeposits = Column(Float)
    investmentdeposits = Column(Float)
    incloandeposits = Column(Float)
    grossnpa = Column(Float)
    netnpa = Column(Float)
    ownersfund_total_source = Column(Float)
    fixed_assets_ta = Column(Float)
    inventory_tr = Column(Float)
    dividend_pr_np = Column(Float)
    dividend_pr_cp = Column(Float)
    earning_retention_ratio = Column(Float)
    cash_earnings_retention = Column(Float)
    price_bv = Column(Float)
    return_sales = Column(Float)
    debt_ta = Column(Float)
    ev = Column(Float)
    pricesalesratio = Column(Float)
    ev_ebita = Column(Float)
    cf_pershare = Column(Float)
    pcf_ratio = Column(Float)
    fcf_share = Column(Float)
    pfcf_ratio = Column(Float)
    fcf_yield = Column(Float)
    scf_ratio = Column(Float)
    gpm = Column(Float)
    salestototalassets = Column(Float)
    salestocurrentassets = Column(Float)
    total_car_basei = Column(Float)
    ti_car_basei = Column(Float)
    tii_car_basei = Column(Float)
    total_car = Column(Float)
    ti_car = Column(Float)
    tii_car = Column(Float)
    npa_gross = Column(Float)
    npa_net = Column(Float)
    npa_advances = Column(Float)
    netprofit_to_pbt = Column(Float)
    pbt_to_pbit = Column(Float)
    pbit_to_sales = Column(Float)
    netprofit_to_sales = Column(Float)
    netsales_to_totalassets = Column(Float)
    return_on_assets = Column(Float)
    assets_to_equity = Column(Float)
    return_on_equity = Column(Float)
    interest_to_debt = Column(Float)
    debt_to_assets = Column(Float)
    interest_to_assets = Column(Float)
    roe_after_interest = Column(Float)
    dividend_payout_per = Column(Float)
    otherincome_to_networth = Column(Float)
    roa_after_interest = Column(Float)
    roe_before_otherinc = Column(Float)
    roe_after_otherinc = Column(Float)
    roe_after_tax_rate = Column(Float)
    credit_deposit = Column(Float)
    interestexpended_interestearned = Column(Float)
    interestincome_totalfunds = Column(Float)
    interestexpended_totalfunds = Column(Float)
    netinterestincome_totalfunds = Column(Float)
    casa = Column(Float)
    inventory_turnover = Column(Float)
    debtors_turnover = Column(Float)
    adj_pe = Column(Float)
    adjusted_bv = Column(Float)
    adj_dps = Column(Float)
    networth_growth = Column(Float)
    ce_growth = Column(Float)
    gb_growth = Column(Float)
    pbdt_growth = Column(Float)
    pbit_growth = Column(Float)
    pbt_growth = Column(Float)
    cp_growth = Column(Float)
    exports_growth = Column(Float)
    imports_growth = Column(Float)
    mcap_growth = Column(Float)
    ebidtam = Column(Float)
    pbdtm = Column(Float)
    lt_debt_equity_ratio = Column(Float)
    roic = Column(Float)
    total_car_b = Column(Float)
    ti_car_b = Column(Float)
    tii_car_b = Column(Float)
    flag = Column(String)


class MonthlyPrice(Base):
    __tablename__ = "monthlyprice"
    __table_args__ = {"schema": "public"}

    fincode = Column(Integer, primary_key=True, index=True)
    month = Column(Integer, primary_key=True)
    year = Column(Integer, primary_key=True)
    scripcode = Column(Integer, index=True)
    open = Column(Numeric)
    high = Column(Numeric)
    low = Column(Numeric)
    close = Column(Numeric)
    volume = Column(Numeric)
    value = Column(Float)
    flag = Column(String)


class NSEMonthPrice(Base):
    __tablename__ = "nse_monthprice"
    __table_args__ = {"schema": "public"}

    fincode = Column(Integer, primary_key=True, index=True)
    month = Column(Integer, primary_key=True)
    year = Column(Integer, primary_key=True)
    symbol = Column(String, index=True)
    open = Column(Numeric)
    high = Column(Numeric)
    low = Column(Numeric)
    close = Column(Numeric)
    volume = Column(Numeric)
    value = Column(Float)
    flag = Column(String)


class CompanyAddress(Base):
    __tablename__ = "companyaddress"
    __table_args__ = {"schema": "public"}

    fincode = Column(Integer, primary_key=True, index=True)
    add1 = Column(String)
    add2 = Column(String)
    add3 = Column(String)
    city_name = Column(String)
    pincode = Column(String)
    state_name = Column(String)
    phone = Column(String)
    fax_no = Column(String)
    website = Column(String)
    e_mail = Column(String)
    flag = Column(String)


class CompanyEquity(Base):
    __tablename__ = "company_equity"
    __table_args__ = {"schema": "public"}

    fincode = Column(Integer, primary_key=True, index=True)
    year_end = Column(Integer, primary_key=True)
    no_shs_subscribed = Column(Numeric)
    latest_equity = Column(Float)
    latest_reserve = Column(Float)
    price = Column(Float)
    mcap = Column(Numeric)
    yield_ = Column("yield", Float)
    fv = Column(Float)
    booknavpershare = Column(Float)
    ttm_yearend = Column(Integer)
    ttmeps = Column(Float)
    ttmpe = Column(Numeric)
    price_sales = Column(Float)
    ev_sales = Column(Float)
    mcap_sales = Column(Float)
    ev = Column(Float)
    price_bv = Column(Float)
    ev_ebitda = Column(Float)
    ttmceps = Column(Float)
    price_ceps = Column(Float)
    pricedate = Column(DateTime)
    stk_exchange = Column(String, index=True)
    flag = Column(String)

